import { userData } from '../app/models/userData';
export const xlsData: userData[] = [
  {
    ID: '123',
    Name: 'jane',
    Desktops: '1',
    DesktopType: 'cloudDesktop2',
    LoginTime: '9:00AM',
    JobType: 'Engineer',
  },
  {
    ID: '345',
    Name: 'jany',
    Desktops: '1',
    DesktopType: 'cloudDesktopPlus2',
    LoginTime: '9:30AM',
    JobType: 'Auditor',
  },
  {
    ID: '456',
    Name: 'jenny',
    Desktops: '3',
    DesktopType: 'cloudDesktop2',
    LoginTime: '10:00AM',
    JobType: 'Sales',
  },
  {
    ID: '789',
    Name: 'john',
    Desktops: '2',
    DesktopType: 'cloudDesktopPlus2',
    LoginTime: '9:00AM',
    JobType: 'marketing',
  },
  {
    ID: '890',
    Name: 'don',
    Desktops: '6',
    DesktopType: 'cloudDesktop2',
    LoginTime: '11.30AM',
    JobType: 'Engineer',
  },
  {
    ID: '876',
    Name: 'mike',
    Desktops: '2',
    DesktopType: 'CloudDesktop2',
    LoginTime: '9:00AM',
    JobType: 'Sales',
  },
  {
    ID: '654',
    Name: 'billy',
    Desktops: '1',
    DesktopType: 'CloudDesktopPlus2',
    LoginTime: '10:00AM',
    JobType: 'Manager',
  },
  {
    ID: '564',
    Name: 'ram',
    Desktops: '2',
    DesktopType: 'CloudDesktop2',
    LoginTime: '9:30AM',
    JobType: 'marketing',
  },
  {
    ID: '753',
    Name: 'shyam',
    Desktops: '1',
    DesktopType: 'CloudDesktop2',
    LoginTime: '9:00AM',
    JobType: 'Manager',
  },
  {
    ID: '447',
    Name: 'suman',
    Desktops: '2',
    DesktopType: 'cloudDesktopPlus2',
    LoginTime: '11:00AM',
    JobType: 'Sales',
  },
];
